### ISSUE TITLE
ValueError: Only call `sparse_softmax_cross_entropy_with_logits`

### ISSUE THREAD

**Issue by isalmanhaider** [uclmr/fakenewschallenge#4]
FOA, Impressive research, read the paper. However, while executing pred.py I get the following error.
If you could please help in this regard.

File "pred.py", line 80, in <module>
    loss = tf.reduce_sum(tf.nn.sparse_softmax_cross_entropy_with_logits(logits, stances_pl) + l2_loss)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 2011, in sparse_softmax_cross_entropy_with_logits
    labels, logits)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1759, in _ensure_xent_args
    "named arguments (labels=..., logits=..., ...)" % name)
ValueError: Only call `sparse_softmax_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)

**Comment by jaminriedel** [comment]
Thank you for your message and raising this issue.

I assume the error stems from the fact that you are probably using a newer version of `TensorFlow`. As indicated, the system was developed, trained, and tested in version 0.12.1 and compatibility with newer versions has not been checked.

Nevertheless, I believe the error can be fixed by changing the order of and naming the arguments passed to the `tf.nn.sparse_softmax_cross_entropy_with_logits()` function. Line 80 in `pred.py` should therefore read:

```python
loss = tf.reduce_sum(tf.nn.sparse_softmax_cross_entropy_with_logits(labels=stances_pl, logits=logits) + l2_loss)
```

Hopefully the above makes sense and solves the issue. If not, please do get in touch again!
